networks:
  localnet:
    name: localnet

services:

  nginx:
    container_name: nginx

    image: nginx:${NGINX_VER}

    ports:
      - 80:80

    volumes:
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www

    networks:
      - localnet

    depends_on:
      - mysql
      - php-fpm

  php-fpm:
    container_name: php-fpm
    
    image: php-fpm

    build:
      context: ./docker/php
      args:
        - USER_ID=${USER_ID}
        - PHP_VER=${PHP_VER}
        - XDEBUG_VER=${XDEBUG_VER}

    volumes:
      - ./www:/var/www

    environment:
      PHP_IDE_CONFIG: serverName=${SERVER_NAME}

    extra_hosts:
      - "host.docker.internal:host-gateway"

    user: ${USER_ID}:${USER_ID}

    networks:
      - localnet

    depends_on:
      - mysql

  mysql:
    container_name: mysql

    image: mariadb:${MARIADB_VER}

    ports:
      - 3306:3306
      
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d

    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    
    networks:
      - localnet

  adminer:
    container_name: adminer

    image: adminer:${ADMINER_VER}

    ports:
      - 8080:8080

    environment:
      - ADMINER_DEFAULT_SERVER=mysql
      - ADMINER_DESIGN=pappu687
    networks:
      - localnet

    depends_on:
      - mysql